[project]
name = "jupyter-notebooks"
version = "0.1.0"
description = "Vault for storing various jupyter notebooks"
requires-python = ">=3.14"
dependencies = [
    "arch>=8.0.0",
    "catboost>=1.2.10",
    "fastparquet>=2025.12.0",
    "jupyter>=1.1.1",
    "kagglehub>=1.0.0",
    "lightgbm>=4.6.0",
    "matplotlib>=3.10.8",
    "mplfinance>=0.12.10b0",
    "optuna>=4.8.0",
    "pandas>=3.0.1",
    "pyarrow>=23.0.1",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "scipy-stubs~=1.17.1",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.6",
    "tsfracdiff>=1.0.4",
    "tsfresh>=0.21.1",
    "xgboost>=3.2.0",
]
